//@host = http://localhost:3000
@host = http://suorita.com

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiSWxra2EiLCJsYXN0TmFtZSI6IlNhbG1lbml1cyIsImVtYWlsIjoiaWxra2Euc2FsbWVuaXVzQGlraS5maSIsInBob25lIjpudWxsLCJyb2xlIjowLCJpYXQiOjE1ODc4MTA4MjZ9.33CN2p9h_132kxfnBrMeVtBRRUch1yPR6fn5yXM2qgI

GET {{host}}/hotline/api/auth/me
x-auth-token: {{token}}
###
POST {{host}}/hotline/api/auth
content-type: application/json

{
  "username": "albert",
  "password": "weber"
}
