@host1 = http://localhost:4000
@host = http://autotechsystems.fi
@endPoint = {{host}}/hotline/api/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJpbGtrYTE4MyIsImZpcnN0TmFtZSI6Iklsa2thIiwibGFzdE5hbWUiOiJTYWxtZW5pdXMiLCJlbWFpbCI6Imlsa2thLnNhbG1lbml1c0Bpa2kuZmkiLCJwaG9uZSI6bnVsbCwicm9sZSI6MCwiaWF0IjoxNjAzOTczNjI2fQ.5HcT19zUgw2pzdzW2gMQyZulpAHF0v55vtqBLF0TpD4

GET {{endPoint}}/test
###
GET {{endPoint}}/me
x-auth-token: {{token}}
###
POST {{endPoint}}/login
content-type: application/json

{
  "username": "ilkka183",
  "password": "weber"
}
###
POST {{endPoint}}/register
content-type: application/json

{
  "groupId": 2,
  "role": 1,
  "firstName": "Matti",
  "lastName": "Meikäläinen",
  "username": "matti.maikalainen@iki.fi",
  "password": "huuhaa",
  "email": "matti.maikalainen@gmail.com",
  "enabled": true
}
