@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiSWxra2EiLCJsYXN0TmFtZSI6IlNhbG1lbml1cyIsImVtYWlsIjoiaWxra2Euc2FsbWVuaXVzQGlraS5maSIsInBob25lIjpudWxsLCJyb2xlIjowLCJpYXQiOjE1ODc4MTA3MTF9.S34etP_fPycmDjNA7qnX_IVY3HyjFGhnTe8bky7mOfY

GET http://localhost:3000/api/ClientGroup?orderBy=Id&sortOrder=ASC
###
GET http://suorita.com/hotline/api/custom/UserGroups
x-auth-token: {{token}}
###
GET http://suorita.com/hotline/api/table/UserGroup/row?Id=2
x-auth-token: {{token}}
###
POST http://localhost:3000/api/ClientGroup
content-type: application/json

{
    "name": "K-Kaara Oy",
    "phone": "050 61698",
    "email": "ilkka.salmenius@gmail.com",
    "enabled": true
}
###
PUT http://localhost:3000/api/ClientGroup/2
content-type: application/json

{
    "country": "Finland",
    "enabled": true
}
###
DELETE http://localhost:3000/api/ClientGroup/8
