@host = http://localhost:3000

GET {{host}}/api/traficom/ZLP-833
###
GET {{host}}/api/traficom/ISI-560
###
GET {{host}}/api/traficom/SIO-913
###
GET http://www.rekisterinumeroapi.com/api/reg.asmx/CheckFinland?RegistrationNumber=SIO-913&username=ilkka183
