@endPoint = http://localhost:4000/hotline/api/traficom

GET {{endPoint}}/ZLP-833
###
GET {{endPoint}}/ISI-561
###
GET {{endPoint}}/SIO-913
###
GET http://www.rekisterinumeroapi.com/api/reg.asmx/CheckFinland?RegistrationNumber=SIO-913&username=ilkka183
