@endPoint = http://autotechsystems.fi/hotline/api/Users

GET {{endPoint}}
###
GET {{endPoint}}/5
###
POST {{endPoint}}
content-type: application/json

{
    "groupId": 2,
    "role": 1,
    "firstName": "Matti",
    "lastName": "Meikäläinen",
    "email": "matti.maikalainen@gmail.com",
    "password": "huuhaa",
    "enabled": true
}
###
PUT {{endPoint}}/5
content-type: application/json

{
    "password": "helppo",
    "enabled": false
}
###
DELETE {{endPoint}}/18
