@host = http://localhost:4000

GET {{host}}/hotline/api/Users
###
GET {{host}}/hotline/api/User/5
###
POST {{host}}/hotline/api/User
content-type: application/json

{
    "groupId": 2,
    "role": 1,
    "firstName": "Matti",
    "lastName": "Meikäläinen",
    "email": "matti.maikalainen@gmail.com",
    "password": "huuhaa",
    "enabled": true
}
###
PUT {{host}}/hotline/api/User/5
content-type: application/json

{
    "password": "helppo",
    "enabled": false
}
###
DELETE {{host}}/hotline/api/User/5
